处理在传入的 spec 中改变特定 key 的问题
leancloud/carmine-sentinel pull request #5
Opened 2020-07-09 06:11 UTC by liuchong

有时候会在传入 spec 的时候，指定一些参数比如传入特定的 `db`。

当一个实例中使用多个不同的 db 时，可能就会触发这个问题，这个改动处理了它。

2020-07-09 06:26 UTC, liuchong commented
```
(defn- merge-not-contains
  "Merge two map, copy key/value from m1 when keys are not contained in m0."
  [m0 m1]
  (merge-with #(if (and %1
                        (and (number? %1)
                             (not= 0 %1)))
                 %1
                 %2)
              m0 m1))
```

或者还可以进一步处理一下默认值，比如数字的 0 👀

2020-07-09 06:53 UTC, liuchong commented
另一个方案是，只处理特定参数，比如就是 `db`

或者可以在这个位置针对特定参数做处理：
https://github.com/leancloud/carmine-sentinel/blob/4f89aa79d48f7ca7103e6680378f23e105627542/src/carmine_sentinel/core.clj#L217

2020-07-09 09:22 UTC, juvenn commented on src/carmine_sentinel/core.clj
> +      (update server-conn :spec merge-not-contains spec))
这里不对诶，我们应该优先取 spec 中的值，而不是 server-conn.spec 里面的值。

因为后者是从 sentinel 拿到的最新值，我们要依赖这个最新值，而不是老的值。

2020-07-09 09:23 UTC, juvenn commented
> 当一个实例中使用多个不同的 db 时，可能就会触发这个问题，这个改动处理了它。

能给我看看，你找到的那个有问题的 db 没有传入的代码吗？我看看整体怎么改比较恰当。

2020-07-09 10:15 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +      (update server-conn :spec merge-not-contains spec))
这里意思是，如果指定了，就用指定的值。

或者我们可以特殊处理特定的参数

2020-07-09 10:30 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +      (update server-conn :spec merge-not-contains spec))
按理来说，:spec 是不需要传入的，如果传入了，可能是想使用这个特定的 :spec。

不直接把两个 spec 反过来 merge，是怕传入值是 nil 的键

2020-07-09 10:36 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +      (update server-conn :spec merge-not-contains spec))
https://github.com/leancloud/carmine-sentinel/blob/4f89aa79d48f7ca7103e6680378f23e105627542/src/carmine_sentinel/core.clj#L217

或者就在这附近，db 之类的一些参数，就不要存了，只拿 host 和 port 就好了

2020-07-09 10:48 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +                                   [:host :port :password])]
或者也可以这样 👀

2020-07-09 14:19 UTC, ylgrgyq commented on src/carmine_sentinel/core.clj
> +                                   [:host :port :password])]
有点晕 为什么只取 host port password ?

2020-07-09 15:16 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +                                   [:host :port :password])]
或者就删掉 db 也行，不太确定还有什么是可能传进来的。

如果取了多余 key 的话，在执行 get-sentinel-redis-spec 的时候，按照以前的方式保存的优先，就会导致请求时临时传入的 spec 的一些需要的字段比如就是 db，被覆盖掉。

第一次指定的参数会被保存，第二次再指定就会不生效因为保存的优先。我做了两个可能的改动，要么这个地方不保存 db 等字段，要么 get-sentinel-redis-spec 的地方用传入的参数覆盖保存的参数。我觉得这两种方式选一种就可以了 :eyes:

2020-07-09 15:25 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +                                   [:host :port :password])]
> https://github.com/leancloud/carmine-sentinel/pull/2/files#r443371381

我检查了一下以前的提交，应该就是这个改动导致的

2020-07-09 23:34 UTC, ylgrgyq commented on src/carmine_sentinel/core.clj
> +                                   [:host :port :password])]
感觉说的通

2020-07-09 23:35 UTC, ylgrgyq commented on src/carmine_sentinel/core.clj
> +                                   [:host :port :password])]
我好像没看出来什么问题，需要本地测试一下看看是否符合预期。
我之前测试就是起两个 redis 起三个 sentinel，然后试试看各种情况是否都符合。

2020-07-10 06:39 UTC, juvenn requested changes

2020-07-10 06:39 UTC, juvenn commented on src/carmine_sentinel/core.clj
> +        server-spec   (select-keys server-spec [:password])]
timeout-ms, db 等参数都被丢弃了，为什么？

2020-07-10 06:39 UTC, juvenn commented on src/carmine_sentinel/core.clj
> +                 (try-resolve-master-spec spec specs sentinel-group master-name)]
其它函数传递的都是 server-conn，为什么要把这个函数的 server-conn 参数改成 spec ?

2020-07-10 06:39 UTC, juvenn commented on src/carmine_sentinel/core.clj
> +       (apply merge {})))
不喜欢这样「反常规」的设计，在一个看起来名字很简单的函数，在实现上却处理了关于 nil 的细节。

这种不直观的抽象，往往给调用方埋坑。

2020-07-10 07:58 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +       (apply merge {})))
那就直接 merge，问题在于后面的 nil 会将前面的有效值覆盖
我都可以，你看看

2020-07-10 08:04 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +        server-spec   (select-keys server-spec [:password])]
就是为了避免先前保存的值在 merge 的时候由于老值优先，而覆盖掉传进来的值，这是方案之一。

update-conn-spec 还做了一个修改，就是传递的新值优先。这样的话其实也可以处理 db 参数被覆盖的问题，这是另外一个方案。

但其实即使使用了 update-conn-spec，这里丢弃其他值也没有什么问题。
这个地方需要的就只是个 password 而已，password 是不太经常变化的，即使变化了也可以调用 reset-resolved-specs 来处理掉。
而其他参数，实际上是传递给接下来调用的那个`常规` wcar 的，这里其实把参数保存下来没有意义。

2020-07-10 08:05 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +        server-spec   (select-keys server-spec [:password])]
我加了一些测试，你看看可以方便理解问题在哪里

2020-07-10 08:08 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +                 (try-resolve-master-spec spec specs sentinel-group master-name)]
server-conn 里面的其他参数用不到，传进来没有意义，而且还让人不能把握到底哪些参数起了作用，造成混乱

第二个参数是 sentinel-specs，这个传 server-spec 显得也比较整齐一点

其实我还有个选项是只传 password，这里没有做这么彻底是暂时保留使用其他参数的可能性

这个参数之前的版本是没有的，我看到最近的一次修改引入了这个参数，这也是造成问题的大致原因

2020-07-10 08:12 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +       (apply merge {})))
就这个 merge-some 而言，我最优先的实现方式是直接使用这个函数来改：

> https://github.com/clojure/clojure/blob/clojure-1.10.1/src/clj/clojure/core.clj#L3041
```
(defn merge
  "Returns a map that consists of the rest of the maps conj-ed onto
  the first.  If a key occurs in more than one map, the mapping from
  the latter (left-to-right) will be the mapping in the result."
  {:added "1.0"
   :static true}
  [& maps]
  (when (some identity maps)
    (reduce1 #(conj (or %1 {}) %2) maps)))
```

但 reduce1 是一个私有函数，无法使用，所以才有了现在的实现方式。

另外我也不认为这个函数反常规，这个函数名字上面也写了，`merge-some`，也就是不是 nil 的值才被 merge 进来。如果这个反常规的话，我们广泛使用的 `assoc-some` 岂不是也反常规了？ 👀

2020-07-10 08:15 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +       (apply merge {})))
这个函数的好处是，传递参数的时候不用把 nil 的 key 删除，nil 的 key 就自动不起作用了。当然也有坏处，就是我们不能通过赋值一个 nil 来强行覆盖掉先前保存的值。

我对选择用或者不用不强求，都可以 👀

2020-07-10 08:22 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +                 (try-resolve-master-spec spec specs sentinel-group master-name)]
当然，另外的办法就是不 merge，把这个参数删掉。
试想一个 master slave 密码不一样的场景，将这个密码保存下来可能没有也什么意义。密码或许应该通过一个类似 `set-sentinel-groups` 的方式设置进来。

2020-07-14 06:52 UTC, juvenn commented on src/carmine_sentinel/core.clj
> +                 (try-resolve-master-spec spec specs sentinel-group master-name)]
> 试想一个 master slave 密码不一样的场景

不，这样的用例暂时不在我们支持的范围。在 sentinel 模式下，使用不同的 password 会让管理异常困难。password 是跟 ip 绑定的，是静态的，他的角色是有可能来回切换 master/slave 。也就是说，不能按照角色来选择 password 。

2020-07-14 06:52 UTC, juvenn commented on src/carmine_sentinel/core.clj
> +      (update server-conn :spec #(merge resolved-spec %)))
我理解你的思路了，甚至很喜欢这个思路。

但是它有一点不好的地方，就是比如在内部，我们有没有可能也要用到 timeout-ms, db 呢？就比如在 make-sure-master-role? ，我们是不是应该传递 timeout-ms 比较好，否则 thread 会不会有 hang up 的问题？

如果说，既要传递 timeout-ms ，又要传递 password 。那我倾向于保留老方案，就是在内存缓存的 master, slave spec 里还是记录 timeout-ms, db 等这些参数比较好。


try-resolve 我还是希望保留之前的 server-conn 参数，因为它还包含了更多的（比如 prefer-slave? ）的信息。同时，我也觉得和其他函数的该参数一致比较好。（如果一定想改的话，我支持在另外一个 pr 里面，把其他函数的参数都改一下也可以。）

2020-07-15 02:54 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +                 (try-resolve-master-spec spec specs sentinel-group master-name)]
password 在 redis 实例上。应该也不会太复杂，把保存下来的信息搞成类似 {:master host :specs {host1 spec1, host2 spec2}} 的结构就好了。
不过我赞成暂不支持这种情况

2020-07-15 02:59 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +      (update server-conn :spec #(merge resolved-spec %)))
内部使用的话，timeout-ms 等参数，应该是我们内部定的，属于库自己的判断，可以写死一些常量，最多可以给一个接口让用户来调节。
传递给 wcar 的参数里面的 timeout-ms 还是不一样的，这个严格来说是针对某一次客户代码向 redis 实例的一次特定连接定义的参数；只不过客户代码一般情况下为了方便都定义了一个 wcar* 宏来每次传递相同的参数
所以我才提出了一个可选项，那就是直接提供一个独立于 wcar 调用接口的单独的 password 设置接口的也是可行的。

2020-07-15 03:09 UTC, liuchong commented on src/carmine_sentinel/core.clj
> +      (update server-conn :spec #(merge resolved-spec %)))
那根据上述评论看上去，方案暂时可以就是 try-resolve-master-spec 里面代码还是保持不变改回去，把后面 update-conn-spec 中 merge 时优先选择传入的参数，并且当传入了 sentinel 信息时，就把 spec 中的 host 和 port 删除。

你觉得是直接 merge 呢还是用之前那个 merge-some 版本？

其实根据我上面一条评论的说法，我觉得保存 password 之外的 spec 中的信息，其实意义不是很大，不过暂时也可以先留着吧。

2020-07-16 06:47 UTC, juvenn commented on src/carmine_sentinel/core.clj
> +      (update server-conn :spec #(merge resolved-spec %)))
> 你觉得是直接 merge 呢还是用之前那个 merge-some 版本？

直接用 merge ，请不要引入 merge-some 。

2020-07-16 08:17 UTC, juvenn approved these changes
LGreatTM :+1:

2020-07-16 08:19 UTC, merged